var slug = require('slug')
const { Product } = require("../models");

// how to called images in html/hs `/images/homepage/${Product.product_name}.jpg`
const productData = [
  {
    product_name: "Gorilla Cool",
    image_name: "gorilla-cool",
    stock: 10,
    price: 79.99,
    type_id: 3,
  },
  {
    product_name: "Game of Thrones",
    image_name: "game-of-thrones",
    stock: 10,
    price: 69.99,
    type_id: 5,
  },
  {
    product_name: "Dark Side Of The Moon",
    image_name: "dark-side-of-the-moon",
    stock: 10,
    price: 69.99,
    type_id: 2,
  },
  {
    product_name: "Mars Attacks",
    image_name: "mars-attacks",
    stock: 10,
    price: 59.99,
    type_id: 1,
  },
  {
    product_name: "Dark Side",
    image_name: "dark-side",
    stock: 10,
    price: 69.99,
    type_id: 6,
  },
  {
    product_name: "Tank Girl Rockets",
    image_name: "tank-girl-rockets",
    stock: 10,
    price: 59.99,
    type_id: 9,
  },
  {
    product_name: "Punisher",
    image_name: "punisher",
    stock: 10,
    price: 39.99,
    type_id: 7,
  },
  {
    product_name: "Cute Cat Faces",
    image_name: "cute-cat-faces",
    stock: 10,
    price: 49.99,
    type_id: 8,
  },
  {
    product_name: "ET And Friends",
    image_name: "et-and-friends",
    stock: 10,
    price: 79.99,
    type_id: 3,
  },
  {
    product_name: "Light At The End",
    image_name: "light-at-the-end",
    stock: 10,
    price: 69.99,
    type_id: 2,
  },
  {
    product_name: "Loony Wrestlers",
    image_name: "loony-wrestlers",
    stock: 10,
    price: 59.99,
    type_id: 1,
  },
  {
    product_name: "Tanooki Mario",
    image_name: "tanooki-mario",
    stock: 10,
    price: 59.99,
    type_id: 4,
  },
  {
    product_name: "Vash The Stampede",
    image_name: "vash-the-stampede",
    stock: 10,
    price: 69.99,
    type_id: 6,
  },
  {
    product_name: "X-Men Chicks",
    image_name: "x-men-chicks",
    stock: 10,
    price: 39.99,
    type_id: 7,
  },
  {
    product_name: "Akira",
    image_name: "akira",
    stock: 10,
    price: 69.99,
    type_id: 6,
  },
  {
    product_name: "All Mad Here",
    image_name: "all-Mad-here",
    stock: 10,
    price: 59.99,
    type_id: 9,
  },
  {
    product_name: "Sky Diving",
    image_name: "sky-diving",
    stock: 10,
    price: 79.99,
    type_id: 3,
  },
  {
    product_name: "Waifu",
    image_name: "waifu",
    stock: 10,
    price: 69.99,
    type_id: 6,
  },
  {
    product_name: "Godzilla",
    image_name: "Godzilla",
    stock: 10,
    price: 49.99,
    type_id: 8,
  },
  {
    product_name: "Diana",
    image_name: "Diana",
    stock: 10,
    price: 59.99,
    type_id: 9,
  },
  {
    product_name: "You Win Or Die",
    image_name: "you-win-or-die",
    stock: 10,
    price: 69.99,
    type_id: 5,
  },
  {
    product_name: "DC Chicks",
    image_name: "dc-chicks",
    stock: 10,
    price: 59.99,
    type_id: 4,
  },
  {
    product_name: "DC Classics",
    image_name: "dc-classics",
    stock: 10,
    price: 99.99,
    type_id: 3,
  },
  {
    product_name: "Ouran Host Club",
    image_name: "ouran-host-club",
    stock: 10,
    price: 59.99,
    type_id: 1,
  },
  {
    product_name: "Cartoon Mayham",
    image_name: "cartoon-mayham",
    stock: 10,
    price: 59.99,
    type_id: 4,
  },
  {
    product_name: "Spider-Man Classic",
    image_name: "spider-man-classic",
    stock: 10,
    price: 69.99,
    type_id: 6,
  },
  {
    product_name: "Borderlands Aviator",
    image_name: "borderlands-aviator",
    stock: 10,
    price: 79.99,
    type_id: 3,
  },
  {
    product_name: "Tank Girl Racer",
    image_name: "tank-girl-racer",
    stock: 10,
    price: 49.99,
    type_id: 8,
  },
  {
    product_name: "Fantic 4 Classics",
    image_name: "fantic-4-classics",
    stock: 10,
    price: 69.99,
    type_id: 5,
  },
  {
    product_name: "OG Gamer",
    image_name: "og-gamer",
    stock: 10,
    price: 69.99,
    type_id: 2,
  },
  {
    product_name: "Ouran Host Club Eating",
    image_name: "ouran-host-club-eating",
    stock: 10,
    price: 39.99,
    type_id: 7,
  },
  {
    product_name: "Tech Takeover",
    image_name: "tech-takeover",
    stock: 10,
    price: 59.99,
    type_id: 9,
  },
  {
    product_name: "Faceless Gambit",
    image_name: "faceless-gambit",
    stock: 10,
    price: 79.99,
    type_id: 3,
  },
  {
    product_name: "Avengers Comics",
    image_name: "avengers-comics",
    stock: 10,
    price: 69.99,
    type_id: 2,
  },
  {
    product_name: "Tis But A Scratch",
    image_name: "tis-but-a-scratch",
    stock: 10,
    price: 59.99,
    type_id: 1,
  },
  {
    product_name: "Self Imposed Strongest Advengers",
    image_name: "Self-Imposed-Strongest-Advengers",
    stock: 10,
    price: 69.99,
    type_id: 5,
  },
  {
    product_name: "One-Punch Man Oppai",
    image_name: "one-punch-man-oppai",
    stock: 10,
    price: 39.99,
    type_id: 7,
  },
  {
    product_name: "Kill Bill",
    image_name: "kill-bill",
    stock: 10,
    price: 59.99,
    type_id: 9,
  },
  {
    product_name: "World of Mario",
    image_name: "world-of-mario",
    stock: 10,
    price: 49.99,
    type_id: 8,
  },
  {
    product_name: "Dead To The World",
    image_name: "dead-to-the-world",
    stock: 10,
    price: 59.99,
    type_id: 4,
  },
  {
    product_name: "Iron Man's Last Stand",
    image_name: "iron-man",
    stock: 10,
    price: 79.99,
    type_id: 3,
  },
  {
    product_name: "The End Of Mario",
    image_name: "the-end-of-mario",
    stock: 10,
    price: 69.99,
    type_id: 6,
  },
  {
    product_name: "Choose Your Character",
    image_name: "choose-your-character",
    stock: 10,
    price: 59.99,
    type_id: 9,
  },
  {
    product_name: "Pop Culture Mini Icons",
    image_name: "pop-culture-mini-icons",
    stock: 10,
    price: 39.99,
    type_id: 7,
  },
  {
    product_name: "Marvel Throwback",
    image_name: "marvel-throwback",
    stock: 10,
    price: 49.99,
    type_id: 8,
  },
  {
    product_name: "Cat In The Cap",
    image_name: "cat-in-the-cap",
    stock: 10,
    price: 79.99,
    type_id: 3,
  },
  {
    product_name: "Never Forget",
    image_name: "never-forget",
    stock: 10,
    price: 59.99,
    type_id: 4,
  },
  {
    product_name: "Deadpool",
    image_name: "Deadpool",
    stock: 10,
    price: 69.99,
    type_id: 6,
  },
  {
    product_name: "To Infinity",
    image_name: "to-infinity",
    stock: 10,
    price: 69.99,
    type_id: 2,
  },
  {
    product_name: "Man Woman Geek",
    image_name: "man-woman-geek",
    stock: 10,
    price: 59.99,
    type_id: 1,
  },
  {
    product_name: "Bat Girls Club",
    image_name: "bat-girls-club",
    stock: 10,
    price: 69.99,
    type_id: 5,
  },
];

const seedProducts = () => Product.bulkCreate(productData);

module.exports = seedProducts;
