var slug = require('slug')
const { Product } = require("../models");

// how to called images in html/hs `/images/homepage/${Product.product_name}.jpg`
const productData = [
  {
    product_name: "Gorilla Cool",
    image_name: slug("Gorilla Cool"),
    stock: 10,
    price: 79.99,
    type_id: 3,
  },
  {
    product_name: "Game of Thrones",
    image_name: slug("Game of Thrones"),
    stock: 10,
    price: 69.99,
    type_id: 5,
  },
  {
    product_name: "Dark Side Of The Moon",
    image_name: slug("Dark Side Of The Moon"),
    stock: 10,
    price: 69.99,
    type_id: 2,
  },
  {
    product_name: "Mars Attacks",
    image_name: slug("Mars Attacks"),
    stock: 10,
    price: 59.99,
    type_id: 1,
  },
  {
    product_name: "Dark Side",
    image_name: slug("Dark Side"),
    stock: 10,
    price: 69.99,
    type_id: 6,
  },
  {
    product_name: "Tank Girl Rockets",
    image_name: slug("Tank Girl Rockets"),
    stock: 10,
    price: 59.99,
    type_id: 9,
  },
  {
    product_name: "Punisher",
    image_name: slug("Punisher"),
    stock: 10,
    price: 39.99,
    type_id: 7,
  },
  {
    product_name: "Cute Cat Faces",
    image_name: slug("Cute Cat Faces"),
    stock: 10,
    price: 49.99,
    type_id: 8,
  },
  {
    product_name: "ET And Friends",
    image_name: slug("ET And Friends"),
    stock: 10,
    price: 79.99,
    type_id: 3,
  },
  {
    product_name: "Light At The End",
    image_name: slug("Light At The End"),
    stock: 10,
    price: 69.99,
    type_id: 2,
  },
  {
    product_name: "Loony Wrestlers",
    image_name: slug("Loony Wrestlers"),
    stock: 10,
    price: 59.99,
    type_id: 1,
  },
  {
    product_name: "Tanooki Mario",
    image_name: slug("Tanooki Mario"),
    stock: 10,
    price: 59.99,
    type_id: 4,
  },
  {
    product_name: "Vash The Stampede",
    image_name: slug("Vash The Stampede"),
    stock: 10,
    price: 69.99,
    type_id: 6,
  },
  {
    product_name: "X-Men Chicks",
    image_name: slug("X-Men Chicks"),
    stock: 10,
    price: 39.99,
    type_id: 7,
  },
  {
    product_name: "Akira",
    image_name: slug("Akira"),
    stock: 10,
    price: 69.99,
    type_id: 6,
  },
  {
    product_name: "All Mad Here",
    image_name: slug("All Mad Here"),
    stock: 10,
    price: 59.99,
    type_id: 9,
  },
  {
    product_name: "Sky Diving",
    image_name: slug("Sky Diving"),
    stock: 10,
    price: 79.99,
    type_id: 3,
  },
  {
    product_name: "Waifu",
    image_name: slug("Waifu"),
    stock: 10,
    price: 69.99,
    type_id: 6,
  },
  {
    product_name: "Godzilla",
    image_name: slug("Godzilla"),
    stock: 10,
    price: 49.99,
    type_id: 8,
  },
  {
    product_name: "Diana",
    image_name: slug("Diana"),
    stock: 10,
    price: 59.99,
    type_id: 9,
  },
  {
    product_name: "You Win Or Die",
    image_name: slug("You Win Or Die"),
    stock: 10,
    price: 69.99,
    type_id: 5,
  },
  {
    product_name: "DC Chicks",
    image_name: slug("DC Chicks"),
    stock: 10,
    price: 59.99,
    type_id: 4,
  },
  {
    product_name: "DC Classics",
    image_name: slug("DC Classics"),
    stock: 10,
    price: 99.99,
    type_id: 3,
  },
  {
    product_name: "Ouran Host Club",
    image_name: slug("Ouran Host Club"),
    stock: 10,
    price: 59.99,
    type_id: 1,
  },
  {
    product_name: "Cartoon Mayham",
    image_name: slug("Cartoon Mayham"),
    stock: 10,
    price: 59.99,
    type_id: 4,
  },
  {
    product_name: "Spider-Man Classic",
    image_name: slug("Spider-Man Classic"),
    stock: 10,
    price: 69.99,
    type_id: 6,
  },
  {
    product_name: "Borderlands Aviator",
    image_name: slug("Borderlands Aviator"),
    stock: 10,
    price: 79.99,
    type_id: 3,
  },
  {
    product_name: "Tank Girl Racer",
    image_name: slug("Tank Girl Racer"),
    stock: 10,
    price: 49.99,
    type_id: 8,
  },
  {
    product_name: "Fantic 4 Classics",
    image_name: slug("Fantic 4 Classics"),
    stock: 10,
    price: 69.99,
    type_id: 5,
  },
  {
    product_name: "OG Gamer",
    image_name: slug("OG Gamer"),
    stock: 10,
    price: 69.99,
    type_id: 2,
  },
  {
    product_name: "Ouran Host Club Eating",
    image_name: slug("Ouran Host Club Eating"),
    stock: 10,
    price: 39.99,
    type_id: 7,
  },
  {
    product_name: "Tech Takeover",
    image_name: slug("Tech Takeover"),
    stock: 10,
    price: 59.99,
    type_id: 9,
  },
  {
    product_name: "Faceless Gambit",
    image_name: slug("Faceless Gambit"),
    stock: 10,
    price: 79.99,
    type_id: 3,
  },
  {
    product_name: "Avengers Comics",
    image_name: slug("Avengers Comics"),
    stock: 10,
    price: 69.99,
    type_id: 2,
  },
  {
    product_name: "Tis But A Scratch",
    image_name: slug("Tis But A Scratch"),
    stock: 10,
    price: 59.99,
    type_id: 1,
  },
  {
    product_name: "Self Imposed Strongest Advengers",
    image_name: slug("Self Imposed Strongest Advengers"),
    stock: 10,
    price: 69.99,
    type_id: 5,
  },
  {
    product_name: "One-Punch Man Oppai",
    image_name: slug("One-Punch Man Oppai"),
    stock: 10,
    price: 39.99,
    type_id: 7,
  },
  {
    product_name: "Kill Bill",
    image_name: slug("Kill Bill"),
    stock: 10,
    price: 59.99,
    type_id: 9,
  },
  {
    product_name: "World of Mario",
    image_name: slug("World of Mario"),
    stock: 10,
    price: 49.99,
    type_id: 8,
  },
  {
    product_name: "Dead To The World",
    image_name: slug("Dead To The World"),
    stock: 10,
    price: 59.99,
    type_id: 4,
  },
  {
    product_name: "Iron Man's Last Stand",
    image_name: slug("Iron Man's Last Stand"),
    stock: 10,
    price: 79.99,
    type_id: 3,
  },
  {
    product_name: "The End Of Mario",
    image_name: slug("The End Of Mario"),
    stock: 10,
    price: 69.99,
    type_id: 6,
  },
  {
    product_name: "Choose Your Character",
    image_name: slug("Choose Your Character"),
    stock: 10,
    price: 59.99,
    type_id: 9,
  },
  {
    product_name: "Pop Culture Mini Icons",
    image_name: slug("Pop Culture Mini Icons"),
    stock: 10,
    price: 39.99,
    type_id: 7,
  },
  {
    product_name: "Marvel Throwback",
    image_name: slug("Marvel Throwback"),
    stock: 10,
    price: 49.99,
    type_id: 8,
  },
  {
    product_name: "Cat In The Cap",
    image_name: slug("Cat In The Cap"),
    stock: 10,
    price: 79.99,
    type_id: 3,
  },
  {
    product_name: "Never Forget",
    image_name: slug("Never Forget"),
    stock: 10,
    price: 59.99,
    type_id: 4,
  },
  {
    product_name: "Deadpool",
    image_name: slug("Deadpool"),
    stock: 10,
    price: 69.99,
    type_id: 6,
  },
  {
    product_name: "To Infinity",
    image_name: slug("To Infinity"),
    stock: 10,
    price: 69.99,
    type_id: 2,
  },
  {
    product_name: "Man Woman Geek",
    image_name: slug("Man Woman Geek"),
    stock: 10,
    price: 59.99,
    type_id: 1,
  },
  {
    product_name: "Bat Girls Club",
    image_name: slug("Bat Girls Club"),
    stock: 10,
    price: 69.99,
    type_id: 5,
  },
];

const seedProducts = () => Product.bulkCreate(productData);

module.exports = seedProducts;
